name: Update Changelog
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        uses: Templum/gitmoji-changelog@main
      - name: Debug GIT Log
        run: git log v0.1.0..HEAD --pretty=format:"%h %s %an [%ae]"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: feature/changelog-update
          title: ":memo: Update Changelog for ${{ steps.outputs.for-version }}"
          commit-message: ":memo: Update Changelog for ${{ steps.outputs.for-version }}"