name: Update Changelog
on:
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Generate Changelog"
        uses: sercanuste/gitmoji-changelog-action@v1
        with:
          add_author: true