name: Create Tag
on:
  workflow_dispatch:
    inputs:
      new_version:
        required: true
        description: "SEMVER Version of the next release"
        type: string
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ github.event.inputs.new_version }}"
          message: ":bookmark: Releasing ${{ github.event.inputs.new_version }}"
          tag_exists_error: true